### ISSUE TITLE
预训练模型和测试视频的网盘链接有误？

### ISSUE THREAD

**Issue by DWCTOD** [YuanxunLu/LiveSpeechPortraits#1]
大佬您好，感谢开源您的优秀工作。项目中的谷歌网盘链接，有误。

**Comment by YuanxunLu** [comment]
Data and models haven't been uploaded yet, thanks for your attention.

**Comment by YuanxunLu** [comment]
Data and models haven't been uploaded yet, thanks for your attention.

**Comment by krokodilno** [comment]
are you going to upload in the near future?

**Comment by Aleskert** [comment]
Maybe you will add instruction for new models?

**Comment by YuanxunLu** [comment]
Data and models have been uploaded. Feel free to comment if you have any questions. Close since it is solved.

**Comment by DWCTOD** [comment]
> Data and models have been uploaded. Feel free to comment if you have any questions. Close since it is solved.

谢谢大佬

**Comment by yaleimeng** [comment]
@YuanxunLu GoogleDrive在国内下载非常困难，经常中断。能否提供其他网盘（如123盘之类）分流下载？
