### ISSUE TITLE
AttributeError: module 'librosa' has no attribute 'output'

### ISSUE THREAD

**Issue by AK391** [YuanxunLu/LiveSpeechPortraits#10]
https://stackoverflow.com/questions/63997969/attributeerror-module-librosa-has-no-attribute-output

would suggest using soundfile instead in demo.py

sf.write(tmp_audio_path, tmp_audio_clip, sr)

**Comment by YuanxunLu** [comment]
Thanks for your feedback. Librosa has removed 'librosa.output' after v0.8.0. soundfile is an alternative io library. I will make it clear in the requirement.txt.
