### ISSUE TITLE
beta1 in train

### ISSUE THREAD

**Issue by X-niper** [YuanxunLu/LiveSpeechPortraits#21]
default bata1 in feature2face training is 0.5, while the article says you train your model with beta1 = 0.9. 
Is beta1 value critical in feature2face training?

Thanks!

**Comment by YuanxunLu** [comment]
Actually, I tried beta1 = 0.5 or 0.9 both in the early experiments, the results are similar.
I think the influence of the beta1 value is not critical.

**Comment by X-niper** [comment]
> Actually, I tried beta1 = 0.5 or 0.9 both in the early experiments, the results are similar. I think the influence of the beta1 value is not critical.

Thanks you!!
