### ISSUE TITLE
questions on feature matching loss. bugs?

### ISSUE THREAD

**Issue by X-niper** [YuanxunLu/LiveSpeechPortraits#24]
Hello, thanks for the great job!

In your code, feature2face_model.py , feature matching loss is computed as part of the D loss, which is then used to optimize discriminator but usually, the feature matching loss is used to optimize the generator and your paper said so.

I wonder whether there is anything wrong with the code..

Thanks!

**Comment by YuanxunLu** [comment]
You're right. I've updated the codes. Thanks for your report!
