### ISSUE TITLE
Audio to Mouth-related Motion

### ISSUE THREAD

**Issue by TimmmYang** [YuanxunLu/LiveSpeechPortraits#25]
Hi, great work! As I read from your paper, one need to get the ground truth mouth displacements to train Audio2Feature model. You mentioned [Shi, 2014; Thies, 2016] to track 3D mouth shape and head pose. Are there any open source tools to help me get these data?

**Comment by YuanxunLu** [comment]
The used tracking tool can be replaced by any 3D facial tracking algorithms, e.g., 3DDFAv2, PRNet, DECA, etc. There is much open-source work targeting single image 3D face reconstruction.
