### ISSUE TITLE
Generate live speech for person arbitrary!!

### ISSUE THREAD

**Issue by pegahsalehi** [YuanxunLu/LiveSpeechPortraits#31]
Thanks for sharing such nice work
Can I run this code for person arbitrary? How the information in the folder is obtained for each person?

Thank you for your help!

**Comment by TimmmYang** [comment]
You can check this paper in Section 4. about implementation details.

**Comment by pegahsalehi** [comment]
> You can check this paper in Section 4. about implementation details.

I read section 4, but I do not know where to start?! What code should I use to make facial landmarks? How to generate npz and npy files? Where can I read cropped video as input?

 Thank you in advance

**Comment by YuanxunLu** [comment]
The proposed method is person-specific, you need to train new models for different people. You can check issue #19 for more details.

**Comment by pegahsalehi** [comment]
Dear Lu,

Thanks in advance for your time to respond.

I desperately need to run LSP code. Would it be possible for you to guide
me a little clearer to train my arbitrary person?

You said that "the repo has included many necessary parts, e.g.,
datasets/options/losses/models. This will help your implementation".
But still I can not understand the order of their implementation and the
details.

I will not forget your kindness!

___________
Best Regard
Pegah Salehi
