### ISSUE TITLE
About how to choose candidate img set 

### ISSUE THREAD

**Issue by zhangziwenHIT** [YuanxunLu/LiveSpeechPortraits#34]
Thank you for your outstanding work!
I don't know how do you understand this sentence in the article:
"Forthe rest, we sample x- and y-axis rotation by uniform intervals and choose the nearest samples from intervals. " in 3.4 'Candidate Image set'.
I do not understand how the last two images were chosen.Can you explain or provide reference code, please!
Thank U!

**Comment by YuanxunLu** [comment]
for example, now you have a x-axis rotation sequence: [-90, -70, -60, -20, 0, 30, 50, 70]
if I want to choose two images, the intervals should be [-36.667, 16.667]
and the resulting two image id will be the one owns the nearest value: -20(id=3) and 30(id=5).
Hope this help for your understanding.
