### ISSUE TITLE
about Image2Image translation inference issue

### ISSUE THREAD

**Issue by huaishuiweizhu** [YuanxunLu/LiveSpeechPortraits#35]
6. Image2Image translation & Saving results...
Image2Image translation inference:   0%|                                                       | 0/672 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 264, in <module>
    facedataset.dataset.image_pad)
  File "C:\Users\23046\LiveSpeechPortraits\datasets\face_dataset.py", line 280, in get_data_test_mode
    feature_map = torch.from_numpy(self.get_feature_image(landmarks, (self.opt.loadSize, self.opt.loadSize), shoulder, pad)[np.newaxis, :].astype(np.float32)/255.)
  File "C:\Users\23046\LiveSpeechPortraits\datasets\face_dataset.py", line 287, in get_feature_image
    im_edges = self.draw_face_feature_maps(landmarks, size)
  File "C:\Users\23046\LiveSpeechPortraits\datasets\face_dataset.py", line 317, in draw_face_feature_maps
    im_edges = cv2.line(im_edges, tuple(keypoints[edge[i]]), tuple(keypoints[edge[i+1]]), 255, 2)
cv2.error: OpenCV(4.5.4) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type

**Comment by huaishuiweizhu** [comment]
这个问题怎么解决。

**Comment by sd707589** [comment]
I had encountered the same problem. Here was my solution:
``` python
ps1 = [int(x) for x in edge[i]]
ps2 = [int(x) for x in edge[i+1]]
im_edges = cv2.line(im_edges, ps1, ps2, 255, 2)
```
Hope it help.

**Comment by supersarr** [comment]
![efde2365cddb6a15c6707e398a18938](https://user-images.githubusercontent.com/74942943/147430238-83b6fd7f-fc2d-4a5f-965a-4cd5a2216072.png)

**Comment by YuanxunLu** [comment]
This is an OpenCV version issue. Please check #29.
