### ISSUE TITLE
Error when run the demo

### ISSUE THREAD

**Issue by muxiddin19** [YuanxunLu/LiveSpeechPortraits#37]
cv2.error: OpenCV(4.5.4) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
I got this error when run the demo. Any solutions, please?

**Comment by fishfl** [comment]
I got the same error, could any one solve this?

**Comment by vicdxxx** [comment]
you guys can change Opencv version opencv_python==4.4.0.40

**Comment by YuanxunLu** [comment]
This is an OpenCV version error. I've merged the PR.
