### ISSUE TITLE
How to generate APC_feature_base.npy of each person?

### ISSUE THREAD

**Issue by vicdxxx** [YuanxunLu/LiveSpeechPortraits#39]
dear fellow
I found manifold projection use APC_feature_base.npy each person, but not clear how to generate this file.
Is that use target person voice to train audio2feature_model?

**Comment by vicdxxx** [comment]
I found the answer is yes

**Comment by YuanxunLu** [comment]
1. APC_feature_base.npy is the generated APC features from training audio sequences of each person, manifold projection learns a mapping from input audio to the training database. Please check the paper.
2. audio2feature model is person-specific, you should train each audio2feature model for each person.

**Comment by vicdxxx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
