### ISSUE TITLE
Can you provide the links for the video sequences used in your paper

### ISSUE THREAD

**Issue by Zhang-Xiaoyi** [YuanxunLu/LiveSpeechPortraits#43]
Hi, I saw you put 8 video sequences in the APPENDIX . But I cannot find what are the web links to the videos to get the exact dataset as you used. Can you provide the eight links? Thanks.

**Comment by YuanxunLu** [comment]
Please check issue #7

**Comment by Zhang-Xiaoyi** [comment]
great. thanks for the prompt reply.
