### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/APC_epoch_160.model'

### ISSUE THREAD

**Issue by AK391** [YuanxunLu/LiveSpeechPortraits#5]
---------- Loading Model: APC-------------
Traceback (most recent call last):
  File "demo.py", line 146, in <module>
    APC_model.load_state_dict(torch.load(config['model_params']['APC']['ckp_path']), strict=False)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './data/APC_epoch_160.model'

**Comment by stephenlechat** [comment]
I ran into the same issue. The file is there, but the folder is named "Input" instead of "input" as mentioned. So this should work: 
python demo.py --id May --driving_audio './data/Input/00083.wav'

**Comment by YuanxunLu** [comment]
> ---------- Loading Model: APC-------------
> Traceback (most recent call last):
> File "demo.py", line 146, in
> APC_model.load_state_dict(torch.load(config['model_params']['APC']['ckp_path']), strict=False)
> File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 594, in load
> with _open_file_like(f, 'rb') as opened_file:
> File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 230, in _open_file_like
> return _open_file(name_or_buffer, mode)
> File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 211, in **init**
> super(_open_file, self).**init**(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: './data/APC_epoch_160.model'

'./data/APC_epoch_160.model' can be downloaded from the Google Drive link in the README.MD

**Comment by YuanxunLu** [comment]
> I ran into the same issue. The file is there, but the folder is named "Input" instead of "input" as mentioned. So this should work:
> python demo.py --id May --driving_audio './data/Input/00083.wav'

Thanks for your feedback. I have updated the README.md.
