### ISSUE TITLE
I have 1 question about mean_pts3d.npy and tracked3D_normalized_pts_fix_contour.npy, can you help me？

### ISSUE THREAD

**Issue by 1615070057** [YuanxunLu/LiveSpeechPortraits#55]
1. Can you explain the difference between a and b? I understand that a is the average of the 3d landmark, and b is the 3d landmark。Please understand I'm so rubbish。THANKS！

**Comment by YuanxunLu** [comment]
'a' is what and also 'b' is what? I have no idea about it for your incomplete information. Please clarify the description.

**Comment by 1615070057** [comment]
> 'a' 是什么，'b' 是什么？由于您的信息不完整，我对此一无所知。请澄清描述。

sorry,   the difference between mean_pts3d.npy and tracked3D_normalized_pts_fix_contour.npy, I understand that mean_pts3d.npy is the average of the 3d landmark, and tracked3D_normalized_pts_fix_contour.npy is the 3d landmark。THANKS！

**Comment by YuanxunLu** [comment]
You're right.

**Comment by 1615070057** [comment]
ok，thank you! Did you normalize the 3D landmark to [-1, 1]? ex: mean_pts3d.npy

**Comment by 1615070057** [comment]
> ok，thank you! Did you normalize the 3D landmark to [-1, 1]? ex: mean_pts3d.npy

ok， I suddenly understand, it's just delta positions.
