### ISSUE TITLE
会提供训练代码？

### ISSUE THREAD

**Issue by foocker** [YuanxunLu/LiveSpeechPortraits#58]

**Comment by YuanxunLu** [comment]
Please check issue #33.

**Comment by foocker** [comment]
> Please check issue #33.

谢谢，还没仔细看论文，这个是一个人物，一套模型？ 如果不是，能讲解下数据制作

**Comment by YuanxunLu** [comment]
Yes, the proposed method is person-specific. For data processing, please check the paper.

**Comment by foocker** [comment]
> Yes, the proposed method is person-specific. For data processing, please check the paper.

谢谢，总结了下，还是有很多细节。有点好奇，看了下历史issue，既然这么多人复现了，怎么没有一个pr的？

**Comment by foocker** [comment]
@YuanxunLu  想问下训练数据集的组织格式是什么样的。 文件树目录，和对应的含义。我大概理了，还有一些细节。

**Comment by foocker** [comment]
@YuanxunLu 训练数据的目录结构方便发一下吗？h5里面的数据是？change_paras中的scale, xc, yc咋计算的？

**Comment by YuanxunLu** [comment]
Releasing the training data & structure is not in the scope of this repo for copyright reasons, check issue #33.

The released code, including training settings, dataset files, etc will help you to train your own model.

**Comment by foocker** [comment]
> Releasing the training data & structure is not in the scope of this repo for copyright reasons, check issue #33.
> 
> The released code, including training settings, dataset files, etc will help you to train your own model.

ok,我重新开了一个问题，希望您可以选择性的回答一些疑问。

**Comment by ak01user** [comment]
我训练出来了，比LiveSpeechPortrait的画面更稳定，演示效果 https://space.bilibili.com/3494353091693235

**Comment by YashVadi** [comment]
@ak01user I am facing difficulty in implementing this. can you please share some of your training code?
