### ISSUE TITLE
Input Discriminator channels

### ISSUE THREAD

**Issue by torphix** [YuanxunLu/LiveSpeechPortraits#62]
Hi I noticed that for the discriminator inputs you have 23 channels.

Why is this? I would have thought the input would have 3 channels for each of the RGB channels in an image

Thanks

**Comment by torphix** [comment]
Also roughly how many epochs on the img synthesis is required before seeing reasonable results?

Ie results that match head pose and  mouth but perhaps with not all visual artificats present?
Thanks, am currently able to synthesise reasonable images but head pose eyes and mouth are all similar

**Comment by YuanxunLu** [comment]
It is a history experiment setting of 'additional 10 history feature maps + 1 current feature maps + 4 candidate images' as G&D input, in which case, 23 = 1 * 1 + 10 * 1 + 4 * 3 for G and add another 3 channels into 26 for D. That didn't work. In my final version, I just use the current feature map as input.

I didn't check these training-related codes carefully and these may confuse you. So, you should set the input channels of D equal to channels of G plus 3.

Training such an image2image translation network is not hard, I believe. I think about 10-20 epochs is enough to synthesize plausible results. If you don't, check whether there are bugs between the input feature maps and the corresponding groundtruth.

Hope the above helps.

**Comment by torphix** [comment]
Thank you! I think my error was simply feeding in the generated images to the discriminator without the sample images + landmarks mask.
Finally do results improve if concatenating the landmark masks for the candidate images along with the target land mark mask ie: providing information of how heads should appear given a specific landmark mask?

Thanks again I very much appreciate your assistance

**Comment by YuanxunLu** [comment]
I'm wondering what is the targe landmark image? The renderer's task is to build a mapping from a feature map to a target image, and therefore the landmark image should be the landmarks of the target image.

**Comment by torphix** [comment]
Makes sense, Thank you!
