### ISSUE TITLE
video crop to 512*512 is the first and 3D face tracking on 512 or ?

### ISSUE THREAD

**Issue by foocker** [YuanxunLu/LiveSpeechPortraits#65]
tracking on original video(not 512*512), and crop the img, landmark to 512*512, using camera transform.

**Comment by YuanxunLu** [comment]
Please check the Sec 4.1 of the paper and you will find what you want.

By the way, whether you track the face first or crop the image first doesn't influence any results of your experiments. Both is OK.

**Comment by foocker** [comment]
> 

ok, thx, the key problem for me is: i am not familiar with the 3d Tracking and i only have a little time to do this.  paper, and code and DECA code i have read a lot. but still have some problem.
