### ISSUE TITLE
what's means of pts_3d, rot_angles, trans?

### ISSUE THREAD

**Issue by foocker** [YuanxunLu/LiveSpeechPortraits#67]
as i have test in DECA, i just get "pose(6),euler_jaw_pose,verts,trans_verts,landmarks2d,landmarks3d,landmarks3d_world and other for rendering resources" but have not found rot_angles, trans, and the dimension is not croresspond. can u explain its means, thx very much.

1. i have read the paper again, pts_3d is facial lamdmark in object coordinate, rot_angles, trans are head pose, rotation and tranlate, which also in object coordinate. is this right? 

2. pts_3d is [-1, 1], rot_angles is [-\pi, \pi], trans is (so large)?

**Comment by YuanxunLu** [comment]
1. Yes
2. range is not important, it depends on your data and how you process it.
