### ISSUE TITLE
Can you share the links of these original videos?

### ISSUE THREAD

**Issue by junleen** [YuanxunLu/LiveSpeechPortraits#7]
Thanks

**Comment by YuanxunLu** [comment]
Yes, but pls wait for some time because I'm busy with other things currently and I need to dig them in a long log file :(

**Comment by YuanxunLu** [comment]
Sorry for the delay. I've checked youtube links of the videos:
1) May: https://www.youtube.com/watch?v=nOj49CzODEU
2) Obama1: https://www.youtube.com/watch?v=25GOnaY8ZCY
3) Obama2: https://www.youtube.com/watch?v=NGEvASSaPyg
4) Nadella: https://www.youtube.com/watch?v=sRtYjVxpMdQ
5) McStay: https://www.youtube.com/watch?v=9IEys7g2YFc

Note that not all frames were used, which was about an average of 3.5 minutes for each video.
